agents/urls.py
from django.urls import path
from agents import views

app_name = 'agents'

urlpatterns = [
    path('', views.AgentListView.as_view(), name="agents-list"),
    path('create/', views.AgentsCreateView.as_view(), name="agents-create"),
    path('<int:pk>/', views.AgentDetailView.as_view(), name="agents-details"),
    path('<int:pk>/update/', views.AgentUpdateView.as_view(), name="agents-update"),
    path('<int:pk>/delete/', views.AgentDeleteView.as_view(), name="agents-delete"),
]

crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from leads.views import LandingPageView, SignupView
from .views import CustomPasswordResetConfirmView
from django.contrib.auth.views import (
    LoginView, 
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from leads import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name="leads-list"),
    path('<int:pk>/', views.LeadDetailView.as_view(), name="leads-details"),
    path('<int:pk>/update/', views.LeadUpdateView.as_view(), name="leads-update"),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name="leads-delete"),
    path('<int:pk>/assign-agent/', views.AssignAgentView.as_view(), name="assign-agent"),
    path('<int:pk>/category/', views.LeadCategoryUpdateView.as_view(), name="lead-category-update"),
    path('create/', views.LeadCreateView.as_view(), name="leads-create"),
    path('categories/', views.CategoryListView.as_view(), name="category-list"),
    path('categories/<int:pk>/', views.CategoryDetailView.as_view(), name="category-detail"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Django Crm</title>
        <link href="{% static 'css/style.css' %}" rel="stylesheet"/>
        <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    </head>
    <body>
        <div class="max-w-7xl mx-auto">
            {% include "navbar.html" %}
            {% block content %}
            {% endblock content %}
        </div>
        {% include "script.html" %}
    </body>
</html>

templates/landing.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="text-gray-700 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
      <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="{% static 'images/dashboard.jpg' %}">
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
            CRM built with Django
        </h1>
        <p class="mb-8 leading-relaxed">
            This CRM helps you manage your leads.
        </p>
        <div class="flex justify-center">
          <a href="{% url 'login' %}" class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">
            Login to get started
          </a>
        </div>
      </div>
    </div>
</section>
{% endblock content %}

templates/navbar.html
<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl">Tailblocks</span>
    </a>
    {% if not request.user.is_authenticated %}
       <a href="{% url 'signup' %}" class="md:mr-auto md:ml-4 md:py-1 md:pl-4 md:border-l md:border-gray-400	flex flex-wrap items-right text-base justify-center">Signup
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
      </a>
      
   {% else %}
      <nav class="md:mr-auto md:ml-4 md:py-1 md:pl-4 md:border-l md:border-gray-400	flex flex-wrap items-right text-base justify-center">
        <a href="{% url 'leads:leads-list' %}" class="mr-5 hover:text-gray-900">Leads</a>
        
        {% if request.user.is_organisor %}
        <a href="{% url 'agents:agents-list' %}" class="mr-5 hover:text-gray-900">Agents</a>
        {% endif %}
      </nav>
    {% endif %}
    {% if request.user.is_authenticated %}
    You are loggedin : {{request.user.username}}
      <form method="POST" action="{% url 'logout' %}">
      {% csrf_token %}
    <button type="submit" class="ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
        Logout
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
            <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
    </button>
      
      
      {% comment %} <a href="{% url 'logout' %}" class="ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Logout
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
      </a> {% endcomment %}
    
    {% else %}
      <a href="{% url 'login' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Signin
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
      </a>
    {% endif %}
  </div>
</header>

templates/script.html
{% load static%}

<script src="{% static 'js/main.js' %}">
</script>